pretrained_model_path: "./checkpoints/stable-diffusion-2-1-unclip-small" 
output_dir: "./outputs/car-turn"
controlnet_pretrained_model_path: [checkpoints/controlnet-2-1-unclip-small-depth]
use_temporal_conv: True

train_data:
  video_dir: "data/car-turn"
  prompt: "a suzuki jimny driving down a mountain road"
  n_sample_frames: 8 
  width: 768
  height: 768
  sample_start_idx: 0
  sample_frame_rate: 1
  condition: [depth]
  video_suffix: .jpg
  condition_suffix: .png
  noise_level: 10000
  image_embed_drop: 0.1
  mask_dir: suzuki-jimny.mask

validation_data:
  prompts:
    - "a suzuki jimny driving down a mountain road in the rain"
    - "a suzuki jimny driving down a mountain road in the rain"

  ref_images: 
    - "data/car-turn/images/0000.jpg"
    - "data/car-turn/images/0000.jpg"

  video_length: 8 # 24
  width: 768
  height: 768
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50 #50
  noise_level: 0
  interpolate_embed_weight: 1.0 ## 1.0 means all use image embedding
  use_masks: true
  start_step: 0 ## start to use mask
  end_step: 50 ## end to use mask
  mask_mode: all # mask_mode: emb / latent / all
  mask_latent_fuse_mode: all # inverse or all
  source_background: false # using source background and changing the protagonist
  source_protagonist: true # using source protagonist and changing the background
  controlnet_conditioning_scale: 1.0

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 200
checkpointing_steps: 200
validation_steps: 200
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
